"""initial

Revision ID: 9c98004113ca
Revises:
Create Date: 2025-08-01 18:17:29.578975

"""

from collections.abc import Sequence
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9c98004113ca"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column(
            "owner",
            sa.String(length=100),
            server_default="teacher",
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum("full", "bitten", "eaten", name="state"),
            server_default="full",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("candies")
    # ### end Alembic commands ###
