"""empty message

Revision ID: 9c9db6f8913e
Revises: 9c98004113ca
Create Date: 2025-08-01 18:23:57.854529

"""
# from typing import Union
from collections.abc import Sequence

# from alembic import op
# import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9c9db6f8913e"
down_revision: str | None = "9c98004113ca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
